export const SAMPLE_PRODUCTS: any[] = [
    {
      'orderID': 95281646,
      'programSpecificKey': '76543ab',
      'transactionCreatedDate': '10/21/2020 20:15:31',
      'osc': 'ERG',
      'shiptoFirstName': 'Dan',
      'shiptoLastName': 'Smith',
      'orderState': 'xxxxxxx',
      'paymentMethod':'Visa',
      'usdAmount': 10.50,
      'localCurrency': 'USD',
      'currencyCode': 'USD',
      'billToFirstName': 'Dan',
      'cbillToLastName': 'Smith',
    }, 
    {
        'orderID': 95281643,
        'programSpecificKey': '76543ab',
        'transactionCreatedDate': '10/21/2020 20:15:31',
        'osc': 'ERG',
        'shiptoFirstName': 'Dan',
        'shiptoLastName': 'Smith',
        'orderState': 'xxxxxxx',
        'paymentMethod':'Visa',
        'usdAmount': 10.50,
        'localCurrency': 'USD',
        'currencyCode': 'USD',
        'billToFirstName': 'Dan',
        'cbillToLastName': 'Smith',
      },
      {
        'orderID': 95281642,
        'programSpecificKey': '76543ab',
        'transactionCreatedDate': '10/21/2020 20:15:31',
        'osc': 'ERG',
        'shiptoFirstName': 'Dan',
        'shiptoLastName': 'Smith',
        'orderState': 'xxxxxxx',
        'paymentMethod':'Visa',
        'usdAmount': 10.50,
        'localCurrency': 'USD',
        'currencyCode': 'USD',
        'billToFirstName': 'Dan',
        'cbillToLastName': 'Smith',
      },
      {
        'orderID': 95281641,
        'programSpecificKey': '76543ab',
        'transactionCreatedDate': '10/21/2020 20:15:31',
        'osc': 'ERG',
        'shiptoFirstName': 'Dan',
        'shiptoLastName': 'Smith',
        'orderState': 'xxxxxxx',
        'paymentMethod':'Visa',
        'usdAmount': 10.50,
        'localCurrency': 'USD',
        'currencyCode': 'USD',
        'billToFirstName': 'Dan',
        'cbillToLastName': 'Smith',
      },
      {
        'orderID': 95281641,
        'programSpecificKey': '76543ab',
        'transactionCreatedDate': '10/21/2020 20:15:31',
        'osc': 'ERG',
        'shiptoFirstName': 'Dan',
        'shiptoLastName': 'Smith',
        'orderState': 'xxxxxxx',
        'paymentMethod':'Visa',
        'usdAmount': 10.50,
        'localCurrency': 'USD',
        'currencyCode': 'USD',
        'billToFirstName': 'Dan',
        'cbillToLastName': 'Smith',
      },
      {
        'orderID': 95281640,
        'programSpecificKey': '76543ab',
        'transactionCreatedDate': '10/21/2020 20:15:31',
        'osc': 'ERG',
        'shiptoFirstName': 'Dan',
        'shiptoLastName': 'Smith',
        'orderState': 'xxxxxxx',
        'paymentMethod':'Visa',
        'usdAmount': 10.50,
        'localCurrency': 'USD',
        'currencyCode': 'USD',
        'billToFirstName': 'Dan',
        'cbillToLastName': 'Smith',
      },
      {
        'orderID': 95281639,
        'programSpecificKey': '76543ab',
        'transactionCreatedDate': '10/21/2020 20:15:31',
        'osc': 'ERG',
        'shiptoFirstName': 'Dan',
        'shiptoLastName': 'Smith',
        'orderState': 'xxxxxxx',
        'paymentMethod':'Visa',
        'usdAmount': 10.50,
        'localCurrency': 'USD',
        'currencyCode': 'USD',
        'billToFirstName': 'Dan',
        'cbillToLastName': 'Smith',
      },
      {
        'orderID': 95281638,
        'programSpecificKey': '76543ab',
        'transactionCreatedDate': '10/21/2020 20:15:31',
        'osc': 'ERG',
        'shiptoFirstName': 'Dan',
        'shiptoLastName': 'Smith',
        'orderState': 'xxxxxxx',
        'paymentMethod':'Visa',
        'usdAmount': 10.50,
        'localCurrency': 'USD',
        'currencyCode': 'USD',
        'billToFirstName': 'Dan',
        'cbillToLastName': 'Smith',
      },
      {
        'orderID': 95281637,
        'programSpecificKey': '76543ab',
        'transactionCreatedDate': '10/21/2020 20:15:31',
        'osc': 'ERG',
        'shiptoFirstName': 'Dan',
        'shiptoLastName': 'Smith',
        'orderState': 'xxxxxxx',
        'paymentMethod':'Visa',
        'usdAmount': 10.50,
        'localCurrency': 'USD',
        'currencyCode': 'USD',
        'billToFirstName': 'Dan',
        'billToLastName': 'Smith',
      }
    ];