// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:61875250-b95f-459a-ba95-7f5b6bbc99d2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0XV1bme2J",
    "aws_user_pools_web_client_id": "6ue7l32tohtpagcdeqrgbfsu43",
    "oauth": {}
};


export default awsmobile;
